services:
  server:
    build: ./server
    container_name: server
    ports:
      - 4000:4000

  auth-front:
    build: ./auth-front
    container_name: auth-frontend
    ports:
      - 3000:3000
    links:
      - server