services:
  auth-backend:
    build: ./auth-backend
    container_name: auth-backend
    ports:
      - 4000:4000

  auth-front:
    build: ./auth-front
    container_name: auth-frontend
    ports:
      - 3000:3000
    links:
      - auth-backend